### ISSUE TITLE
Navigation sidebar "flash" when toggling optional fields

### ISSUE THREAD

**Issue by hamishtaplin** [ONSdigital/eq-author-app#275]
### Expected behaviour

No visual side-effects from toggling optional fields

### Actual behaviour

When toggling optional fields, the title of the current page will "flash" in the navigation sidebar

### Steps to reproduce the behaviour

1. On a question page
1. Toggle an optional field
1. Title of that field should "flash" in the navigation sidebar

**Comment by hamishtaplin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Move existing optional fields to the properties panel (9)](https://trello.com/c/m7c0m75w/734-move-existing-optional-fields-to-the-properties-panel-9)

**Comment by tgandrews** [comment]
This happens on any page update. It is caused by the optimistic response setting the `displayName` to `""` which is incorrect.

The optimistic response can be set to return the correct displayName but would need to pull the value out of the HTML for title. 

It could use the old `displayName` but `withEntityEditor` does not send it to it. Maybe this optimistic response should be removed (added for question properties) be removed until we solve this.

**Comment by tgandrews** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Navigation sidebar flash](https://trello.com/c/J8n5v5uS/1008-navigation-sidebar-flash)
